[build]
  command = "yarn generate"
  publish = "dist"
  functions = "/.netlify/functions"

[dev]
  port = 8888
  publish = "/dist"
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200