[build]
  command = "yarn generate"
  publish = "dist"
  functions = "/functions"

[dev]
  port = 8888
  publish = "/dist"
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/functions/:splat"
  status = 200